// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ClipAutosaveController from "./clip_autosave_controller"
application.register("clip-autosave", ClipAutosaveController)

import ClipSceneListController from "./clip_scene_list_controller"
application.register("clip-scene-list", ClipSceneListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MediaPreviewController from "./media_preview_controller"
application.register("media-preview", MediaPreviewController)

import SceneListController from "./scene_list_controller"
application.register("scene-list", SceneListController)
