// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipPreviewController from "./clip_preview_controller"
import HelloController from "./hello_controller"
application.register("clip-preview", ClipPreviewController)
application.register("hello", HelloController)
